### ISSUE TITLE
check_in 报错

### ISSUE THREAD

**Issue by qyjandroid** [gaoxiaoduan/jj-qiandao#1]
![image](https://user-images.githubusercontent.com/6645414/187574372-99906f36-ec31-4a25-8257-428065a73897.png)

**Comment by gaoxiaoduan** [comment]
@qyjandroid Hi～
1.可以先检查一下USERID、UUID等配置是否正确
2.若要自动拿游戏奖励，必须要玩过一次游戏（报错就是这个原因），玩过一次之后就不会报错了

**Comment by qyjandroid** [comment]
一会试试，谢谢！企业微信推送最新申请的应用推送应该不行了吧，我看说是2022年6月份以前申请的才可以



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月31日 09:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [gaoxiaoduan/jj-qiandao] check_in 报错 (Issue #1) |

@qyjandroid Hi～
1.可以先检查一下USERID、UUID等配置是否正确
2.若要自动拿游戏奖励，必须要玩过一次游戏（报错就是这个原因），玩过一次之后就不会报错了

**Comment by gaoxiaoduan** [comment]
@qyjandroid  Welcome PR
