### ISSUE TITLE
被检测出来了。。有没有办法能避免

### ISSUE THREAD

**Issue by jacktpy** [gaoxiaoduan/jj-qiandao#5]
近期检测到掘友存在违规现象，违规版块为：用户中心-每日签到，具体违规现象为：“脚本签到：当日签到，但在稀土掘金双端无活跃记录”，违规次数为：6次。本次为提醒，如本周仍出现违规现象，会暂停掘友账户参与用户中心相关功能一周时间，

**Comment by gaoxiaoduan** [comment]
要找到双端活跃的track才行，账号活跃起来呗～近期可以先不用这个

**Comment by jacktpy** [comment]
> 要找到双端活跃的track才行，账号活跃起来呗～近期可以先不用这个

 暂时也只能这样了😄
